package main

// Fig2dev - Translates figures generated by xfig to other formats
// Homepage: https://mcj.sourceforge.net/

import (
	"fmt"
	
	"os/exec"
)

func installFig2dev() {
	// Método 1: Descargar y extraer .tar.gz
	fig2dev_tar_url := "https://downloads.sourceforge.net/project/mcj/fig2dev-3.2.9.tar.xz"
	fig2dev_cmd_tar := exec.Command("curl", "-L", fig2dev_tar_url, "-o", "package.tar.gz")
	err := fig2dev_cmd_tar.Run()
	if err != nil {
		fmt.Println("Error al descargar .tar.gz:", err)
		return
	}
	exec.Command("tar", "-xzf", "package.tar.gz").Run()

	// Método 2: Descargar y extraer .zip
	fig2dev_zip_url := "https://downloads.sourceforge.net/project/mcj/fig2dev-3.2.9.tar.xz"
	fig2dev_cmd_zip := exec.Command("curl", "-L", fig2dev_zip_url, "-o", "package.zip")
	err = fig2dev_cmd_zip.Run()
	if err != nil {
		fmt.Println("Error al descargar .zip:", err)
		return
	}
	exec.Command("unzip", "package.zip").Run()

	// Método 3: Descargar binario precompilado
	fig2dev_bin_url := "https://downloads.sourceforge.net/project/mcj/fig2dev-3.2.9.tar.xz"
	fig2dev_cmd_bin := exec.Command("curl", "-L", fig2dev_bin_url, "-o", "binary.bin")
	err = fig2dev_cmd_bin.Run()
	if err != nil {
		fmt.Println("Error al descargar binario:", err)
		return
	}
	exec.Command("chmod", "+x", "binary.bin").Run()
	exec.Command("./binary.bin").Run()

	// Método 4: Descargar y compilar desde código fuente
	fig2dev_src_url := "https://downloads.sourceforge.net/project/mcj/fig2dev-3.2.9.tar.xz"
	fig2dev_cmd_src := exec.Command("curl", "-L", fig2dev_src_url, "-o", "source.tar.gz")
	err = fig2dev_cmd_src.Run()
	if err != nil {
		fmt.Println("Error al descargar código fuente:", err)
		return
	}
	exec.Command("tar", "-xzf", "source.tar.gz").Run()
	exec.Command("make").Run()

	// Método 5: Ejecutar binario directo
	fig2dev_cmd_direct := exec.Command("./binary")
	err = fig2dev_cmd_direct.Run()
	if err != nil {
		fmt.Println("Error al ejecutar binario:", err)
		return
	}
	// Instalar dependencias
	fmt.Println("Instalando dependencia: ghostscript")
exec.Command("latte", "install", "ghostscript")
	fmt.Println("Instalando dependencia: libpng")
exec.Command("latte", "install", "libpng")
	fmt.Println("Instalando dependencia: netpbm")
exec.Command("latte", "install", "netpbm")
}
