package main

// Qcachegrind - Visualize data generated by Cachegrind and Calltree
// Homepage: https://apps.kde.org/kcachegrind/

import (
	"fmt"
	
	"os/exec"
)

func installQcachegrind() {
	// Método 1: Descargar y extraer .tar.gz
	qcachegrind_tar_url := "https://download.kde.org/stable/release-service/24.08.0/src/kcachegrind-24.08.0.tar.xz"
	qcachegrind_cmd_tar := exec.Command("curl", "-L", qcachegrind_tar_url, "-o", "package.tar.gz")
	err := qcachegrind_cmd_tar.Run()
	if err != nil {
		fmt.Println("Error al descargar .tar.gz:", err)
		return
	}
	exec.Command("tar", "-xzf", "package.tar.gz").Run()

	// Método 2: Descargar y extraer .zip
	qcachegrind_zip_url := "https://download.kde.org/stable/release-service/24.08.0/src/kcachegrind-24.08.0.tar.xz"
	qcachegrind_cmd_zip := exec.Command("curl", "-L", qcachegrind_zip_url, "-o", "package.zip")
	err = qcachegrind_cmd_zip.Run()
	if err != nil {
		fmt.Println("Error al descargar .zip:", err)
		return
	}
	exec.Command("unzip", "package.zip").Run()

	// Método 3: Descargar binario precompilado
	qcachegrind_bin_url := "https://download.kde.org/stable/release-service/24.08.0/src/kcachegrind-24.08.0.tar.xz"
	qcachegrind_cmd_bin := exec.Command("curl", "-L", qcachegrind_bin_url, "-o", "binary.bin")
	err = qcachegrind_cmd_bin.Run()
	if err != nil {
		fmt.Println("Error al descargar binario:", err)
		return
	}
	exec.Command("chmod", "+x", "binary.bin").Run()
	exec.Command("./binary.bin").Run()

	// Método 4: Descargar y compilar desde código fuente
	qcachegrind_src_url := "https://download.kde.org/stable/release-service/24.08.0/src/kcachegrind-24.08.0.tar.xz"
	qcachegrind_cmd_src := exec.Command("curl", "-L", qcachegrind_src_url, "-o", "source.tar.gz")
	err = qcachegrind_cmd_src.Run()
	if err != nil {
		fmt.Println("Error al descargar código fuente:", err)
		return
	}
	exec.Command("tar", "-xzf", "source.tar.gz").Run()
	exec.Command("make").Run()

	// Método 5: Ejecutar binario directo
	qcachegrind_cmd_direct := exec.Command("./binary")
	err = qcachegrind_cmd_direct.Run()
	if err != nil {
		fmt.Println("Error al ejecutar binario:", err)
		return
	}
	// Instalar dependencias
	fmt.Println("Instalando dependencia: graphviz")
	exec.Command("latte", "install", "graphviz").Run()
	fmt.Println("Instalando dependencia: qt")
	exec.Command("latte", "install", "qt").Run()
}
