#!/bin/bash

# Ruta a la carpeta de fórmulas
FORMULAS_DIR="formulas"

# Verificar si la carpeta formulas existe, si no crearla
if [ ! -d "$FORMULAS_DIR" ]; then
  echo "Creating $FORMULAS_DIR directory..."
  mkdir -p "$FORMULAS_DIR"
fi

# Lista de herramientas por categorías
TOOLS=(
  "node"
  "yarn"
  "go"
  "python3"
  "pip"
  "ruby"
  "rails"
  "rust"
  "cargo"
  "java"
  "maven"
  "gradle"
  "php"
  "composer"
  "dotnet"
  "clang"
  "gcc"
  "cmake"
  "bazel"
  "vscode"
  "vim"
  "emacs"
  "wireshark"
  "netcat"
  "tcpdump"
  "ncat"
  "traceroute"
  "curl"
  "wget"
  "openssl"
  "nikto"
  "sqlmap"
  "hydra"
  "aircrack-ng"
  "kali-tools"
  "metasploit"
  "burpsuite"
  "john"
  "docker"
  "docker-compose"
  "kubernetes"
  "kubectl"
  "helm"
  "minikube"
  "terraform"
  "ansible"
  "vagrant"
  "azurecli"
  "gcloud"
  "eksctl"
  "podman"
  "mysql"
  "postgresql"
  "sqlite"
  "redis"
  "mongo"
  "influxdb"
  "elasticsearch"
  "cassandra"
  "neo4j"
  "dgraph"
  "nginx"
  "apache"
  "haproxy"
  "http-server"
  "lighthouse"
  "live-server"
  "webpack"
  "parcel"
  "git-lfs"
  "hub"
  "gh"
  "circleci"
  "jenkins-cli"
  "gitlab-runner"
  "htop"
  "tmux"
  "screen"
  "fzf"
  "bat"
  "exa"
  "fd"
  "ripgrep"
  "duf"
  "ncdu"
  "lazygit"
  "hyperfine"
  "asciinema"
  "jq"
)

# Crear los archivos vacíos
for tool in "${TOOLS[@]}"; do
  FILE="$FORMULAS_DIR/$tool.go"
  if [ ! -f "$FILE" ]; then
    echo "Creating $FILE..."
    touch "$FILE"
  else
    echo "$FILE already exists."
  fi
done

echo "All tool files created successfully in $FORMULAS_DIR."
