name: Fleet CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  Fleet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.23.x


      - name: Check Go environment
        run: go version

      - name: Ensure module structure
        run: |
          if [ ! -d "./cli" ] || [ ! -d "./formulas" ]; then
            echo "Error: cli or formulas directory is missing."
            exit 1
          fi

      - name: Install dependencies
        run: |
          go clean -modcache
          go mod tidy || true
          go get -v -t ./... || true

      - name: Verify imports
        run: go build ./...

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Build
        run: go build -o resq

